ci_models_laricchiuta = {
    ("N2", "N2"): ("laricchiuta", {"param_priority": "polarisability"}),
    ("N2", "O2"): ("laricchiuta", {"param_priority": "polarisability"}),
    ("N2", "N"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("N2", "O"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("N2", "NO"): ("laricchiuta", {"param_priority": "polarisability"}),
    ("O2", "N2"): ("laricchiuta", {"param_priority": "polarisability"}),
    ("O2", "O2"): ("laricchiuta", {"param_priority": "polarisability"}),
    ("O2", "N"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("O2", "O"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("O2", "NO"): ("laricchiuta", {"param_priority": "polarisability"}),
    ("N", "N2"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("N", "O2"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("N", "N"):   ("laricchiuta", {"param_priority": "polarisability"}),
    ("N", "O"):   ("laricchiuta", {"param_priority": "polarisability"}),
    ("N", "NO"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("O", "N2"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("O", "O2"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("O", "N"):   ("laricchiuta", {"param_priority": "polarisability"}),
    ("O", "O"):   ("laricchiuta", {"param_priority": "polarisability"}),
    ("O", "NO"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("NO", "N2"): ("laricchiuta", {"param_priority": "polarisability"}),
    ("NO", "O2"): ("laricchiuta", {"param_priority": "polarisability"}),
    ("NO", "N"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("NO", "O"):  ("laricchiuta", {"param_priority": "polarisability"}),
    ("NO", "NO"): ("laricchiuta", {"param_priority": "polarisability"}),
}

ci_models_wright = {
    ("N2", "N2"): ("wright", {"eval_acc":True}),
    ("N2", "O2"): ("wright", {"eval_acc":True}),
    ("N2", "N"):  ("wright", {"eval_acc":True}),
    ("N2", "O"):  ("wright", {"eval_acc":True}),
    ("N2", "NO"): ("wright", {"eval_acc":True}),
    ("O2", "N2"): ("wright", {"eval_acc":True}),
    ("O2", "O2"): ("wright", {"eval_acc":True}),
    ("O2", "N"):  ("wright", {"eval_acc":True}),
    ("O2", "O"):  ("wright", {"eval_acc":True}),
    ("O2", "NO"): ("wright", {"eval_acc":True}),
    ("N", "N2"):  ("wright", {"eval_acc":True}),
    ("N", "O2"):  ("wright", {"eval_acc":True}),
    ("N", "N"):   ("wright", {"eval_acc":True}),
    ("N", "O"):   ("wright", {"eval_acc":True}),
    ("N", "NO"):  ("wright", {"eval_acc":True}),
    ("O", "N2"):  ("wright", {"eval_acc":True}),
    ("O", "O2"):  ("wright", {"eval_acc":True}),
    ("O", "N"):   ("wright", {"eval_acc":True}),
    ("O", "O"):   ("wright", {"eval_acc":True}),
    ("O", "NO"):  ("wright", {"eval_acc":True}),
    ("NO", "N2"): ("wright", {"eval_acc":True}),
    ("NO", "O2"): ("wright", {"eval_acc":True}),
    ("NO", "N"):  ("wright", {"eval_acc":True}),
    ("NO", "O"):  ("wright", {"eval_acc":True}),
    ("NO", "NO"): ("wright", {"eval_acc":True}),
}
